##
## Copyright 2020-present by A. Mathis Group and contributors. All rights reserved.
##
## This project and all its files are licensed under GNU AGPLv3 or later version. 
## A copy is included in dlc2action/LICENSE.AGPL.
##

# set; the keys to include
keys: !!set {"coords_heatmap", "motion_heatmap"}
channel_policy: "color" # ["color", "black&white", "bp"]; if "black&white" the heatmaps have one channel and all keypoints are equivalent, if "color" each keypoint is assigned a unique color, if "bp" each keypoint has a separate channel
heatmap_width: 128 # int; the width of the heatmaps in pixels
sigma: 0.7 # float; the standard deviation of the gaussian kernel (0 for no smoothing)
