##
## Copyright 2020-present by A. Mathis Group and contributors. All rights reserved.
##
## This project and all its files are licensed under GNU AGPLv3 or later version. 
## A copy is included in dlc2action/LICENSE.AGPL.
##
kernel_size: 25 # int; kernel size
mid_channels: [128, 160] # list; middle channels
input_dims: "dataset_features" # int | str; the number of input features (leave as "dataset_features" to compute it automatically)
