##
## Copyright 2020-present by A. Mathis Group and contributors. All rights reserved.
##
## This project and all its files are licensed under GNU AGPLv3 or later version. 
## A copy is included in dlc2action/LICENSE.AGPL.
##

# set; a set of augmentations (from 'rotate', 'real_lens', 'add_noise', 'shift', 'zoom', 'mirror', 'switch')
augmentations: !!set {'add_noise', 'mirror'}
use_default_augmentations: true # bool; if true, the default augmentation list will be used (['mirror', 'shift', 'add_noise'])
rotation_limits: [-1.57, 1.57] # list; list of rotation angle limits in radians ([low, high])
# set; set of dimensions that can be mirrored (0 for x, 1 for y, 2 for z)
mirror_dim: !!set {0}
noise_std: 0.003 # float; standard deviation of noise
zoom_limits: [0.5, 1.5] # list; list of float zoom limits ([low, high])
masking_probability: 0.1 # float; the probability of masking a joint
bodyparts_order: 'dataset_bodyparts' # list; a list of bodypart names
graph_features: false # bool; if true, the output tensor will be reshaped to fit graph networks
