##
## Copyright 2020-present by A. Mathis Group and contributors. All rights reserved.
##
## This project and all its files are licensed under GNU AGPLv3 or later version. 
## A copy is included in dlc2action/LICENSE.AGPL.
##
model_name: 'ms_tcn3' # str; model name (run project.help("model") for more info)
num_classes: 'dataset_classes' # int; number of classes
exclusive: ??? # bool; if true, single-label classification is used; otherwise multi-label
ssl: null # set; a set of SSL names to use
# set; set of metric names (run project.help("metrics") for more info)
metric_functions: !!set {'f1', 'recall', 'precision'}
loss_function: 'ms_tcn' # str; name of loss function
feature_extraction: 'kinematic' # str; the feature extraction method (only 'kinematic' at the moment)
only_load_annotated: true # bool; if true, the input files that don't have a matching annotation file will be disregarded
ignored_clips: null # list; a list of string clip ids (agent names) to be ignored
num_cpus: 5 # int; the number of CPUs to use in data processing (by default all are used)
len_segment: 128 # int; the length of segments (in frames) to cut the videos into
overlap: 96 # int; the overlap (in frames) between neighboring segments
interactive: false # bool; if true, annotations are assigned and features are computed for pairs of clips (animals)
