#
# DLC2Action is not open-sourced yet.
# https://choosealicense.com/no-permission/
#
"""
## Augmentations and feature concatenation

Input data in `dlc2action` is stored in feature dictionaries right up until being passed to a model.
That makes it possible to define universal augmentations and SSL transformations that work on a range of datasets
naturally. Those dictionaries are generated by a *feature extractor* when a `dlc2action.data.base_store.InputStore`
instance is initialised. They are
then (optionally) processed by SSL transformations (see `dlc2action.ssl) and finally merged into tensors by
*transformers*. `dlc2action.transformer.base_transformer.Transformer` instances
can also perform augmentations before the merging.
"""

from dlc2action.transformer.kinematic import KinematicTransformer
